import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Nav from "@/components/bussiness/Nav";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen bg-gray-50`}>
        <div className="flex flex-col min-h-screen">
          <header className="sticky top-0 z-50 bg-white shadow-sm p-6 flex items-center gap-20">
            <h1>My Web3 Journey</h1>
            <Nav />
          </header>
          <main className="flex-1 container mx-auto px-4 py-8 flex justify-center items-center">
            {children}
          </main>
          <footer className="bg-white border-t">
            <div className="container mx-auto px-4 py-6">
              <p className="text-center text-gray-600">© 2025 Catch Yan</p>
            </div>
          </footer>
        </div>
      </body>
    </html>
  );
}
